package com.example.hrm_game.data.entity.game;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.List;

@Entity
@Table(name = "achievement")
@RequiredArgsConstructor
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(description = "User achievements entity")
public class AchievementEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Achievement id generated by db")
    private Long id;
    @ApiModelProperty(value = "Achievement description", example = "First victory!")
    private String description;
    @ApiModelProperty(value = "Achievement adding date")
    private LocalDate localDate;
    @ApiModelProperty(value = "Achievement image")
    private String image;
    @ApiModelProperty(value = "Achievement total progress for adding")
    private Integer total;
    @OneToMany(mappedBy = "achievement")
    private List<UsersAchievementEntity> usersAchievement;
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "quest_achievement", referencedColumnName = "id")
    private QuestEntity quest;
}
