package com.example.hrm_game.data.entity.game;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "quests")
@RequiredArgsConstructor
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(description = "Quest entity")
public class QuestEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("Quest id generated by db")
    private Long id;
    @ApiModelProperty(value = "Quest title name", example = "Kill 10 goblins")
    private String title;
    @ApiModelProperty(value = "Quest description", example = "Goblins attacked our village. Find their lair and bring me 10 of their ears")
    private String description;
    @ApiModelProperty(value = "Experience given for the quest")
    private Integer experience;
    @ApiModelProperty(value = "Money given for the quest")
    private Integer coins;
    @ApiModelProperty(value = "Quest icon")
    private String image;
    @ApiModelProperty(value = "Quest total progress for adding")
    private Integer total;
    @OneToOne(mappedBy = "quest")
    private AchievementEntity achievement;
    @OneToMany(mappedBy = "quests")
    private List<UsersQuestsEntity> userQuests;
    private Integer reputation;
}
