package com.example.hrm_game.data.entity.equipment;

import com.example.hrm_game.data.entity.game.UserEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.springframework.beans.factory.annotation.Value;

import javax.persistence.*;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "chest")
@RequiredArgsConstructor
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(description = "Chest entity")
public class ChestEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Chest id generated by db")
    private Long id;
    @ApiModelProperty(value = "Chest icon")
    private String image;
    @ApiModelProperty(value = "Chest name", example = "Fighting Spirit Armor")
    private String name;
    @ApiModelProperty(value = "Chest description",
            example = "The spirit of the ancient spirit of war. When you put it on, you feel a surge of power.")
    private String description;
    @ApiModelProperty(value = "Armor amount")
    @Value("${some.key:0}")
    private int armor;
    @ApiModelProperty(value = "Strength amount")
    @Value("${some.key:0}")
    private int strength;
    @ApiModelProperty(value = "Mana amount")
    @Value("${some.key:0}")
    private int mana;
    @ApiModelProperty(value = "Health amount")
    @Value("${some.key:0}")
    private int health;
    @ApiModelProperty(value = "Agility amount")
    @Value("${some.key:0}")
    private int agility;
    @ApiModelProperty(value = "Intelligence amount")
    @Value("${some.key:0}")
    private int intelligence;
    @OneToMany(mappedBy = "chest", fetch = FetchType.EAGER)
    private List<UserEntity> user;
    @ManyToMany(mappedBy = "chests", fetch = FetchType.EAGER)
    private Set<InventoryEntity> chestsInventory;
}
