package com.example.hrm_game.data.entity.equipment;

import com.example.hrm_game.data.entity.game.UserEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import javax.persistence.*;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "defender")
@RequiredArgsConstructor
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(description = "Defender entity")
public class DefenderEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Defender id generated by db")
    private Long id;
    @ApiModelProperty(value = "Defender icon")
    private String image;
    @ApiModelProperty(value = "Defender name", example = "Citadel wall")
    private String name;
    @ApiModelProperty(value = "Defender description",
            example = "Protects like once the walls of the native citadel")
    private String description;
    //TODO: сделать энам DefenderType
    @ApiModelProperty(value = "Defender type", example = "PLATE")
    private String type;
    @ApiModelProperty(value = "Strength amount")
    private Long strength;
    @ApiModelProperty(value = "Agility amount")
    private Long agility;
    @ApiModelProperty(value = "Intelligence amount")
    private Long intelligence;
    @ApiModelProperty(value = "Armor amount")
    private Long armor;
    @OneToMany(mappedBy = "defender")
    private List<UserEntity> user;
    @ManyToMany(mappedBy = "defenders")
    private Set<InventoryEntity> inventory;
}
