package com.example.hrm_game.data.entity.equipment;

import com.example.hrm_game.data.entity.game.UserEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import javax.persistence.*;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "helmets")
@RequiredArgsConstructor
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(description = "Helmet entity")
public class HelmetEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Helmet id generated by db")
    private Long id;
    @ApiModelProperty(value = "Helmet icon")
    private String image;
    @ApiModelProperty(value = "Helmet name", example = "Helm of Fortitude")
    private String name;
    @ApiModelProperty(value = "Helmet description", example = "It's time to butt with bulls")
    private String description;
    @ApiModelProperty(value = "Armor amount")
    private Long armor;
    @ApiModelProperty(value = "Strength amount")
    private Long strength;
    @ApiModelProperty(value = "Mana amount")
    private Long mana;
    @ApiModelProperty(value = "Health amount")
    private Long health;
    @ApiModelProperty(value = "Agility amount")
    private Long agility;
    @ApiModelProperty(value = "Intelligence amount")
    private Long intelligence;
    @OneToMany(mappedBy = "helmet", fetch = FetchType.EAGER)
    private List<UserEntity> user;
    @ManyToMany(mappedBy = "helmets", fetch = FetchType.EAGER)
    private Set<InventoryEntity> helmetsInventory;
}
